version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

# Explicitly set the version of Python and its requirements
python:
  install:
    #- requirements: doc/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - doc
        - cache
